language: r
warnings_are_errors: true
sudo: required
before_install:
- openssl aes-256-cbc -K $encrypted_bc07143af10a_key -iv $encrypted_bc07143af10a_iv
  -in tests/testthat/cred.RDS.enc -out tests/testthat/cred.RDS -d
r_packages:
- covr
- lintr
after_success:
- Rscript -e 'covr::codecov()'
- Rscript -e 'covr::coveralls()'
- Rscript -e 'lintr::lint_package()'
